spring:
  application:
    name: demo

server:
  port: 8443
  ssl:
    # Accepting HTTPS connections only
    enabled: true
    # The path to the keystore containing the certificate
    key-store: classpath:keystore.p12
    # The password used to generate the certificate
    key-store-password: tomcat
    # The format used for the keystore
    key-store-type: PKCS12
    # The alias mapped to the certificate
    key-alias: tomcat

#logging:
#  level:
#    com.example: DEBUG
#    org: DEBUG